import { Metadata } from "next"


export const metadata: Metadata = {
    title: 'About Next App',
    // description: 'Generated by create next app',
  }
// для сео можно доюавлять на любую страницу титле и тд

export default function About() {
    return <h1>Select About</h1>
}