import TheHeader from '@/components/TheHeader'
import './globals.css'
import { Inter } from 'next/font/google'
import TheFooter from '@/components/TheFooter'
import { Providers } from '@/components/Providers'
import { Metadata } from 'next'
// шрифты можно самому любой вставить

const inter = Inter({ subsets: ['latin'] })
// настройка шрифтов

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// тут тайтел страницы

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <TheHeader />
          <main className='container'>
            {children}
          </main>
          <TheFooter />
        </Providers>
      </body>
    </html>
  )
}
// обязательно должен быть один лояут
// сюда добавляем компонеты
